diplo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from data import views as data_views
from home import views as home_views
from django_markdown import flatpages
admin.autodiscover()
flatpages.register()

urlpatterns = [
    url(r'^$', home_views.Index.as_view(), name='home'),
    url(r'^glossario/', include('glossario.urls')),
    #url(r'^$', data_views.Home.as_view(), name='home', kwargs={'dashboard': '', 'localidades': 'munic'}),
    url(r'^painel/(?P<slug>[-\w]+)/$', data_views.DashboardDetail.as_view(), name='dashboard-detail'),
    url(r'^painel/(?P<slug>[-\w]+)/(?P<localidade_id>\d+)/$', data_views.DashboardDetail.as_view(), name='dashboard-detail'),
    url(r'^fluxo/$', data_views.IndicadorFluxoChart.as_view(), name='indicador-fluxo-detail', kwargs={"pk": "*"}),
    url(r'^fluxo/(?P<pk>\*|\d+)/$', data_views.IndicadorFluxoChart.as_view(), name='indicador-fluxo-detail'),
    url(r'^fluxo/(?P<pk>\*|\d+)/download/$', data_views.download_fluxo_csv, name='download-fluxo-csv'),
    # url(r'^tema/$', data_views.TemaList.as_view(), name='tema-list'),
    url(r'^tema/mapa/$', data_views.IndicadorMapList.as_view(), name='indicador-map-list', kwargs={'tema': ''}),
    url(r'^tema/$', data_views.IndicadorList.as_view(), name='indicador-list', kwargs={'tema': ''}),
    url(r'^tema/mapa/(?P<tema>\d+)/$', data_views.IndicadorMapList.as_view(), name='indicador-map-list'),
    url(r'^painel-tematico/(?P<slug>[-\w\d]+)/$', data_views.CategoriaDetail.as_view(), name='categoria-detail'),
    url(r'^tema/mapa/(?P<tema>\d+)/(?P<pk>\d+)/$', data_views.IndicadorMap.as_view(), name='indicador-map-detail'),
    url(r'^tema/mapa/(?P<tema>\d+)/(?P<pk>\d+)/(?P<regionalizacao>[-\w]+)/$', data_views.IndicadorMap.as_view(), name='indicador-map-detail'),
    url(r'^tema/grafico/(?P<tema>\d+)/(?P<pk>\d+)/$', data_views.IndicadorChart.as_view(), name='indicador-chart-detail'),
    url(r'^tema/grafico/(?P<tema>\d+)/(?P<pk>\d+)/(?P<regionalizacao>[-\w]+)/$', data_views.IndicadorChart.as_view(), name='indicador-chart-detail'),
    url(r'^tema/dados/(?P<tema>\d+)/(?P<pk>\d+)/$', data_views.IndicadorDetail.as_view(), name='indicador-detail'),
    url(r'^tema/dados/(?P<tema>\d+)/(?P<pk>\d+)/(?P<regionalizacao>[-\w]+)/$', data_views.IndicadorDetail.as_view(), name='indicador-detail'),
    url(r'^tema/dados/(?P<tema>\d+)/$', data_views.IndicadorList.as_view(), name='indicador-list'),
    url(r'^download/dados/(?P<pk>\d+)/(?P<regionalizacao>\w+)/$', data_views.download_csv, name='download-csv'),
    url(r'^dados-primarios/', data_views.DadoPrimarioList.as_view(), name='dado-primario-list'),
    url(r'^conteudo/', include('django.contrib.flatpages.urls')),
    url(r'^markdown/', include( 'django_markdown.urls')),
    url(r'^admin/', admin.site.urls),
]

admin.site.site_header = 'Painel de Controle'

home/models.py
# coding=utf-8
from __future__ import unicode_literals

from django.db import models
from django.utils.six import python_2_unicode_compatible
from treebeard.mp_tree import MP_Node


@python_2_unicode_compatible
class MenuItem(MP_Node):
    label = models.CharField(max_length=60)
    url = models.CharField(max_length=200)

    class Meta:
        verbose_name = u"Ítem de menu"
        verbose_name_plural = u"Ítens de menu"

    def __str__(self):
        return self.label


@python_2_unicode_compatible
class Conteudo(models.Model):
    TIPO = (
        ('html', 'HTML'),
        ('markdown', 'Markdown'),
    )
    ordem = models.PositiveIntegerField(default=1)
    tipo = models.CharField(max_length=30, default='html', choices=TIPO)
    css = models.CharField(max_length=100, blank=True, null=True)
    corpo = models.TextField()

    class Meta:
        ordering = ('ordem',)

    def __str__(self):
        return "Conteudo Home {}".format(self.ordem)


@python_2_unicode_compatible
class ConteudoRodape(models.Model):
    TIPO = (
        ('html', 'HTML'),
        ('markdown', 'Markdown'),
    )
    ordem = models.PositiveIntegerField(default=1)
    tipo = models.CharField(max_length=30, default='html', choices=TIPO)
    css = models.CharField(max_length=100, blank=True, null=True)
    corpo = models.TextField()

    class Meta:
        ordering = ('ordem',)

    def __str__(self):
        return "Conteudo Rodapé {}".format(self.ordem)

data/forms.py
# coding=utf-8
from django import forms

from data.models import Tema, Localidade, Dashboard


class TemaLocalForm(forms.Form):
    tema = forms.ModelChoiceField(queryset=Tema.objects.filter(dashboard=True), label=u'Escolha um tema', widget=forms.Select(attrs={"onchange":'recarrega(this)'}))
    localidades = forms.ChoiceField(choices=Localidade.TIPO, label=u'Regionalização', widget=forms.Select(attrs={"onchange":'recarrega(this)'}))


class DashboardLocalForm(forms.Form):
    dashboard = forms.ModelChoiceField(queryset=Dashboard.objects.filter(publicado=True), label=u'Painel temático', widget=forms.Select(attrs={"onchange":'recarrega(this)'}))
    localidades = forms.ChoiceField(choices=Localidade.TIPO, label=u'Regionalização', widget=forms.Select(attrs={"onchange":'recarrega(this)'}))

home/views.py
from django.contrib.flatpages.models import FlatPage
from django.views.generic import TemplateView

from data.models import Categoria
from home.models import Conteudo


class Index(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        d = super(Index, self).get_context_data(**kwargs)
        d['categorias'] = Categoria.objects.filter(depth=1, home=True).exclude(slug='fluxos-dos-servicos-de-saude').order_by('ordem')
        d['conteudo_home'] = FlatPage.objects.get(url='/conteudo/home/').content
        d['conteudos'] = Conteudo.objects.all()
        d['fluxos'] = Categoria.objects.get(slug='fluxos-dos-servicos-de-saude')
        return d

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static bootstrap3 %}
{% load sekizai_tags %}
{% load diplo %}
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Gestão Regional e Redes</title>
    {% render_block 'css' %}
    {% addtoblock 'css' %}
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
    {% endaddtoblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js"></script>
    <script>
        WebFont.load({
            google: {
                families: ['Open Sans', 'Lato', 'Oswald']
            }
        });
    </script>
</head>

<body>

    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <img src="{% static 'img/logomarca.svg' %}" alt="logo" class="img-responsive">
                </li>
                <li>
                    <a href="{% url 'home' %}">
                        <i class="fa fa-home"></i>
                        Home</a>
                </li>
                <li>
                    <a href="#lista-de-paineis" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="lista-de-paineis">
                        <i class="fa fa-dashboard"></i>
                        Paineis Temáticos</a>
                    <div id="lista-de-paineis" class="collapse">
                        <ul class="nav level-1">
                            {% for item in menu_paineis %}
                                {% static_page_link item %}
                            {% endfor %}
                        </ul>
                    </div>

                </li>
                <li>
                    <a href="#lista-de-temas" {% if not object %}class="collapsed"{% endif %} data-toggle="collapse" role="button" aria-expanded="false" aria-controls="lista-de-temas">
                        <i class="fa fa-foo"></i>
                        Indicadores</a>
                    <div id="lista-de-temas" class="{% if object %}in {% endif %}collapse">
                        <ul class="nav level-1">
                            {% for entry in lista_categorias %}
                                {% include 'categoria-menu-entry.html' with entry=entry %}
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'admin:index' %}" target="_blank">
                        <i class="fa fa-cog"></i>
                        Administração</a>
                </li>
                <li>
                    <a href="{% url 'admin:logout' %}?next={{ request.path }}">
                        <i class="fa fa-lock"></i>
                        Logout</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'admin:login' %}?next={{ request.path }}">
                        <i class="fa fa-unlock"></i>
                        Login</a>
                </li>
                {% endif %}
            </ul>
            <a href="" class="btn btn-xs menu-toggle right" aria-hidden="true"><i class="fa fa-chevron-left"></i></a>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        {% block breadcrumbs %}
                        <ol class="breadcrumb">
                            {% block crumbs %}
                                <li class="active"><a href="{% url 'home' %}">
                                    <i class="fa fa-dashboard"></i>
                                    Dashboards</a></li>
                            {% endblock %}
                        </ol>
                        {% endblock %}
                        {% block content %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

        <a href="" class="btn btn-xs menu-toggle left" aria-hidden="true"><i class="fa fa-chevron-right"></i></a>
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    {% bootstrap_javascript jquery=1 %}

    <!-- Fallback for Bootstrap Core JavaScript -->
    <script>$.fn.modal || document.write('<script src="{% static "js/bootstrap.min.js" %}">\x3C/script>')</script>

    <!-- Menu Toggle Script -->
    <script>
    $(".menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
    {% render_block 'js' %}
    {% block extra %}{% endblock %}
</body>

</html>

templates/categoria-detail.html
{% extends 'index-base.html' %}

{% block conteudo %}
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li><a href="{% url 'home' %}">Home</a></li>
            <li><a href="{% url 'home' %}">Indicadores</a></li>
            <li class="active">{{ object.nome }}</li>
        </ol>
    </div>
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-3">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {{ object.nome }}
                    </div>
                    <div class="panel-body">
                        <ul class="nav nav-pills nav-stacked">
                            {% for subcategoria in object.get_children %}
                                {% if subcategoria.is_leaf %}
                                    <li><a >{{ subcategoria }}</a></li>
                                {% else %}
                                    <li class="btn btn-primary disabled">{{ subcategoria }}</li>
                                    <li>
                                        <ul class="nav nav-pills nav-stacked">
                                            {% for subsubcategoria in subcategoria.get_children %}
                                                <li><a>{{ subsubcategoria }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                    <h1 class="text-center">{{ object.nome }}</h1>
                    <p class="text-center">{{ object.subtitulo }}</p>
            </div>
        </div>
    </div>

{% endblock %}

templates/categoria-list.html
{% extends 'index-base.html' %}

{% block conteudo %}

{% endblock %}

templates/categoria-menu-entry.html
{% load diplo %}
{% with variaveis=entry.variaveis  %}
    {% if entry.is_leaf and variaveis %}
        <li>
            <a href="#categoria-{{ entry.pk }}" class="{% if object.categoria_id != entry.pk %}collapsed{% endif %}" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="categorias-{{ entry.pk }}"><i class="fa fa-foo"></i> {{ entry.nome }}</a>
            <div id="categoria-{{ entry.pk }}" class="{% if object.categoria_id == entry.pk %}in {% endif %}collapse">
                <ul class="nav level-{{ entry.depth|add:1 }}">
                    {% for indicador in variaveis %}
                        <li{% if object.pk == indicador.pk %} class="active"{% endif %}>
                            {% if indicador.subgrupo %}
                                <a href="{% url 'indicador-fluxo-detail' pk=indicador.pk %}">{{ indicador.nome }}</a>
                            {% else %}
                                <a href="{% url 'indicador-detail' tema=indicador.tema_id pk=indicador.pk %}">{{ indicador.nome }}</a>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </li>
    {% elif entry.get_children_count %}
        <li>
            <a href="#categoria-{{ entry.pk }}" class="{% if not entry|is_parent:object %}collapsed{% endif %}" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="categorias-{{ entry.pk }}"><i class="fa fa-foo"></i> {{ entry.nome }}</a>
            <div id="categoria-{{ entry.pk }}" class="{% if entry|is_parent:object %}in {% endif %}collapse">
                <ul class="nav level-{{ entry.depth|add:1 }}">
                    {% for subentry in entry.get_children %}{% include 'categoria-menu-entry.html' with entry=subentry %}{% endfor %}
                </ul>
            </div>
        </li>
    {% endif %}
{% endwith %}

templates/home.html
{% extends 'base.html' %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>
<div class="well">
    <h1>Exemplo de Gráfico</h1>
    {{ chart.as_html }}
</div>
{% endblock %}

templates/index-base.html
<!doctype html>
{% load static %}
{% load diplo %}
{% load django_markdown %}
{% load sekizai_tags %}
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Saúde em Dados</title>
    {% render_block 'css' %}
    {% addtoblock 'css' %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway:200,400" rel="stylesheet">
    <link rel='stylesheet' type='text/css' href='{% static 'fontawesome/css/font-awesome.min.css' %}' />
    {% endaddtoblock %}
    <style>
        {% render_block 'style' %}
    </style>

    {% addtoblock 'style' %}
        body {
            padding-top: 80px;
            font-family: "Open Sans", Helvetica, sans-serif;
        }
        .navbar.navbar-default.navbar-fixed-top {
            height: 80px;
            background-color: white;
        }
        .navbar-nav > li > a {
            height: 80px;
            padding-top: 30px;
            padding-bottom: 30px;
        }
        .navbar {min-height: 80px !important;}
        div.footer {
            background-color: #0b5e56;
            color: white;
            padding: 10px 0;
        }
    {% endaddtoblock %}

</head>
<body>
<!-- Static navbar -->
{% block navbar %}
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Exibir navegação</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                <img src="{% static 'img/logomarca.svg' %}" alt="Gestão Regional e Redes" style="width: 200px">
            </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                {% for item in top_menu %}
                    {% static_page_link item %}
                {% endfor %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</nav>
{% endblock %}

{% block conteudo %}{% endblock %}

{% block footer %}
    <hr>
    <div class="footer">
    {% for conteudo in conteudos_rodape %}
        <div class="container {{ conteudo.css }}">
            {% if conteudo.tipo == 'markdown' %}
                {{ conteudo.corpo|markdown }}
            {% else %}
                {{ conteudo.corpo|safe }}
            {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% addtoblock 'js' %}
    <script src="http://code.jquery.com/jquery-2.2.4.min.js"
            integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% endaddtoblock %}
{% render_block 'js' %}
</body>
</html>

templates/index.html
{% extends 'index-base.html' %}
{% load static %}
{% load django_markdown %}
{% load sekizai_tags %}

{% block conteudo %}
    {% addtoblock 'css' %}
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    {% endaddtoblock %}
    {% addtoblock 'style' %}
        #bigphoto {
        background-image: url({% static 'img/medico.jpg' %});
        -webkit-background-size: cover;
        background-size: cover;
        width: 100%;
        margin: 0;
        padding: 60px 0 0;
        top: 0;
        left: 0;
        color: white;
        }
        #bigphoto h1, #bigphoto p {
        font-family: Raleway, sans-serif;
        font-weight: 200;
        }
        #bigphoto h1 {
        font-size: 50px;
        }
        div.cards { margin-top: 60px;}
        a.card {
        display: block;
        color: white;
        text-decoration: none;
        padding: 120px 30px 30px;
        transition: background-color 0.8s;
        }
        a.card div {
            position: absolute;
            bottom: 0;
            width: 80%;
        }
        .card.card-0 {
        background-color: rgba(11, 94, 86, 0.5);
        padding: 30px;
        }
    {% endaddtoblock %}

<div id="bigphoto">
    <div class="container">
        {% with conteudo=conteudos|first  %}
            <div class="{{ conteudo.css }}">
                {% if conteudo.tipo == 'markdown' %}
                    {{ conteudo.corpo|markdown }}
                {% else %}
                    {{ conteudo.corpo|safe }}
                {% endif %}
            </div>
        {% endwith %}
        <div class="row cards">
            <a href="{% url 'dado-primario-list' %}" class="card col-xs-12 card-0">
                <h3>Dados primários</h3>
                <p>Fontes de dados da pesquisa</p>
            </a>
            {% for categoria in categorias|slice:'0:6' %}
                {% with indicador=categoria.indicador %}
                <a {% if indicador %}href="{% url 'indicador-detail' tema=indicador.tema_id pk=indicador.pk %}" {% endif %}class="card col-lg-4 col-md-6 card-{% cycle 1 2 3 4 5 6 %}">
                    <div>
                        <h3>{{ categoria.nome }}</h3>
                        <p>{{ categoria.subtitulo }}</p>
                    </div>
                </a>

                {% endwith %}
            {% endfor %}
        </div>
    </div>
</div>
{% if categorias|length > 6 %}
    <div class="container">
        <div class="row" style="background-color: gray">
            {% for categoria in categorias|slice:'6:' %}
                {% with indicador=categoria.indicador %}
                    {% if indicador %}
                    <a href="{% url 'indicador-detail' tema=indicador.tema_id pk=indicador.pk %}" class="card col-lg-4 col-md-6 card-{% cycle 1 2 3 4 5 6 %}">
                        <div>
                            <h3>{{ categoria.nome }}</h3>
                            <p>{{ categoria.subtitulo }}</p>
                        </div>
                    </a>
                    {% endif %}
                {% endwith %}
            {% endfor %}
        </div>
    </div>
{% endif %}
<div class="container">
    <div class="row">
        <a href="{% url 'indicador-fluxo-detail' pk='*' %}" class="card col-xs-12 card-0">
            <h3>{{ fluxos.nome }}</h3>
            <p>{{ fluxos.subtitulo }}</p>
        </a>
    </div>
</div>

{% for conteudo in conteudos|slice:'1:' %}
    <hr>
    <div class="container {{ conteudo.css }}">
        {% if conteudo.tipo == 'markdown' %}
            {{ conteudo.corpo|markdown }}
        {% else %}
            {{ conteudo.corpo|safe }}
        {% endif %}
    </div>
{% endfor %}

{% endblock %}

templates/indicador-detail-base.html
{% extends 'base.html' %}
{% load diplo %}
{% load bootstrap3 %}
{% load sekizai_tags %}

{% block crumbs %}
    {% with tema=object.tema %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'indicador-list' tema='' %}">Dados</a></li>
        {% if object.categoria %}
            {% for ancestor in object.categoria.get_ancestors %}
            <li>{{ ancestor.nome }}</li>
            {% endfor %}
            <li>{{ object.categoria.nome }}</li>
        {% endif %}
        <li class="active"><a href="{% url 'indicador-detail' tema=tema.pk pk=object.pk %}">{{ object.nome }}</a></li>
    {% endwith %}
{% endblock %}

{% block content %}
    {% if object != fluxo %}
    <script>
        function recarrega(el) {
            window.location = '/tema/{% block tipo %}dados{% endblock %}/{{ object.tema_id }}/{{ object.pk }}/' + $('#id_localidades').val() + '/';
        }
    </script>
        <form id="form_tema" action="" class="form form-horizontal">
            <div class="row">
                {% bootstrap_field form.localidades layout='horizontal' form_group_class='form-group col-lg-12' %}
            </div>
        </form>

    <ul class="nav nav-tabs">
        <li role="presentation"{% block dados %} class="active"{% endblock %}><a href="{% url 'indicador-detail' tema=object.tema_id pk=object.pk regionalizacao=regionalizacao %}"><i class="fa fa-table"></i> Dados</a></li>
        <li role="presentation"{% block mapa %}{% endblock %}><a href="{% url 'indicador-map-detail' tema=object.tema_id pk=object.pk regionalizacao=regionalizacao %}"><i class="fa fa-map"></i> Mapas</a></li>
        <li role="presentation"{% block grafico %}{% endblock %}><a href="{% url 'indicador-chart-detail' tema=object.tema_id pk=object.pk regionalizacao=regionalizacao %}"><i class="fa fa-info-circle"></i> Informações</a></li>
    </ul>
    <h1 class="text-center"><small>{{ object.categoria }}:</small>
        <br> {{ object.nome }}</h1>
    {% endif %}
{% endblock %}

templates/indicador-detail-chart.html
{% extends 'indicador-detail-base.html' %}
{% load diplo %}
{% load bootstrap3 %}
{% load static %}
{% load sekizai_tags %}
{% load django_markdown %}

{% block dados %}{% endblock %}
{% block tipo %}grafico{% endblock %}
{% block grafico %} class="active"{% endblock %}

{% block content %}
    {{ block.super }}
    <div id="data-table-container">
        <h3 class="text-center">Medadados</h3>
        <table class="table">
            <tbody>
            <tr>
                <th class="text-right" style="width: 20%;">Descrição:</th>
                <td>{{ object.descricao|default:'-' }}</td>
            </tr>
            <tr>
                <th class="text-right">Período:</th>
                <td>{{ object.periodo|ul_split:',' }}</td>
            </tr>
            <tr>
                <th class="text-right">Fonte:</th>
                <td>
                    <ul>
                        {% for fonte in object.fontes.all %}
                            <li>{{ fonte.nome }}</li>
                        {% empty %}
                            <li>ND/NA</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
            <tr>
                <th class="text-right">Observações:</th>
                <td>{{ object.observacao|markdown }}</td>
            </tr>
            <tr>
                <th class="text-right">Tema:</th>
                <td>{{ object.tema|default:'-' }}</td>
            </tr>
            </tbody>
        </table>
        <p></p>
        <hr>
    </div>
{% endblock %}

templates/indicador-list.html
{% extends 'base.html' %}
{% load diplo %}
{% load bootstrap3 %}

{% block crumbs %}
    {% with tema=object_list.first.tema %}
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'indicador-list' tema=tema.pk %}">Dados</a></li>
        <li class="active"><a href="{% url 'indicador-list' tema=tema.pk %}">{{ tema.nome }}: indicadores</a></li>
    {% endwith %}
{% endblock %}

{% block content %}
    <script>
        function recarrega(el) {
            window.location = '/tema/' + $('#id_tema').val() + '/';
        }
    </script>
    <form id="form_tema" action="" class="form form-horizontal">
        <div class="row">
            {% bootstrap_field form.tema layout='horizontal' form_group_class='form-group col-lg-12' %}
        </div>
    </form>

    <h1 class="text-center"><small>Tema:</small> {{ object_list.first.tema }}</h1>
    <h3>Escolha um indicador:</h3>

    <table class="table table-striped">
        <tr>
            <th>Indicador</th>
            <th>Período</th>
        </tr>
        {% for object in object_list %}
        <tr>
            <td><a href="{% url 'indicador-detail' tema=object.tema_id pk=object.pk %}">{{ object.nome }}</a></td>
            <td>{{ object.periodo|compacta }}</td>
        </tr>
        {% endfor %}
    </table>
{% endblock %}